FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package.json ./
COPY package-lock.json ./

# Install any needed packages
RUN npm install

# Bundle app source
COPY . .

# Your app binds to port 80
EXPOSE 80

# Define environment variable
ENV NAME World

# Run the app
CMD [ "npm", "start" ]