FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# Bundle app source
COPY . .

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Your app binds to port 42000 so you'll use the EXPOSE instruction to have it mapped by the docker daemon
EXPOSE 42000

CMD [ "node", "script/index.js" ]